config/routes.rb
Rails.application.routes.draw do
  root 'sedes#index'
  resources :sedes do
    resources :empleados
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
  belongs_to :sede
end

app/models/sede.rb
class Sede < ApplicationRecord
    has_many :empleados
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: %i[ show edit update destroy ]
  before_action :get_sede

  # GET /empleados or /empleados.json
  def index
    @empleados = @sede.empleados
  end

  # GET /empleados/1 or /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados or /empleados.json
  def create
    @sede = Sede.find_by(id: params[:sede_id])
    @empleado = Empleado.new(empleado_params)
    @empleado.sede_id = params[:sede_id]
    respond_to do |format|
      if @empleado.save
        format.html { redirect_to sede_empleado_path(@sede, @empleado), notice: "Empleado was successfully created." }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1 or /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: "Empleado was successfully updated." }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1 or /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: "Empleado was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    def get_sede
      @sede = Sede.find(params[:sede_id])
    end

    # Only allow a list of trusted parameters through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :apellido, :edad, :email, :sede_id)
    end
end

app/controllers/sedes_controller.rb
class SedesController < ApplicationController
  before_action :set_sede, only: %i[ show edit update destroy ]

  # GET /sedes or /sedes.json
  def index
    @sedes = Sede.all
  end

  # GET /sedes/1 or /sedes/1.json
  def show
  end

  # GET /sedes/new
  def new
    @sede = Sede.new
  end

  # GET /sedes/1/edit
  def edit
  end

  # POST /sedes or /sedes.json
  def create
    @sede = Sede.new(sede_params)

    respond_to do |format|
      if @sede.save
        format.html { redirect_to @sede, notice: "Sede was successfully created." }
        format.json { render :show, status: :created, location: @sede }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sedes/1 or /sedes/1.json
  def update
    respond_to do |format|
      if @sede.update(sede_params)
        format.html { redirect_to @sede, notice: "Sede was successfully updated." }
        format.json { render :show, status: :ok, location: @sede }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sedes/1 or /sedes/1.json
  def destroy
    @sede.destroy
    respond_to do |format|
      format.html { redirect_to sedes_url, notice: "Sede was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sede
      @sede = Sede.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sede_params
      params.require(:sede).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/sedes_helper.rb
module SedesHelper
end

app/views/empleados/_form.html.erb
<%= form_with(model: [@sede, @empleado]) do |form| %>
  <% if empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
        <% empleado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editing Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Show', @empleado %> |
<%= link_to 'Back', empleados_path %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Email</th>
      <th>Sede</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.nombre %></td>
        <td><%= empleado.apellido %></td>
        <td><%= empleado.edad %></td>
        <td><%= empleado.email %></td>
        <td><%= empleado.sede_id %></td>
        <td><%= link_to 'Show', sede_empleado_path(@sede, empleado) %></td>
        <td><%= link_to 'Edit', edit_sede_empleado_path(@sede, empleado) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empleado', new_sede_empleado_path(@sede) %>

app/views/empleados/new.html.erb
<h1>New Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Back', sede_empleados_path(@sede) %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @empleado.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @empleado.apellido %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @empleado.edad %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empleado.email %>
</p>

<p>
  <strong>Sede:</strong>
  <%= @empleado.sede_id %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServiciosCompany</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sedes/_form.html.erb
<%= form_with(model: sede) do |form| %>
  <% if sede.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sede.errors.count, "error") %> prohibited this sede from being saved:</h2>

      <ul>
        <% sede.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sedes/edit.html.erb
<h1>Editing Sede</h1>

<%= render 'form', sede: @sede %>

<%= link_to 'Show', @sede %> |
<%= link_to 'Back', sedes_path %>

app/views/sedes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sedes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sedes.each do |sede| %>
      <tr>
        <td><%= sede.nombre %></td>
        <td><%= link_to 'Show', sede %></td>
        <td><%= link_to 'Edit', edit_sede_path(sede) %></td>
        <td><%= link_to 'Destroy', sede, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Listar Empleados', sede_empleados_path(sede) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sede', new_sede_path %>

app/views/sedes/new.html.erb
<h1>New Sede</h1>

<%= render 'form', sede: @sede %>

<%= link_to 'Back', sedes_path %>

app/views/sedes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @sede.nombre %>
</p>

<%= link_to 'Edit', edit_sede_path(@sede) %> |
<%= link_to 'Back', sedes_path %>